version: '3'

services:

  nginx: #name of the container
    image: nginx:cproesch
    build: requirements/nginx
    restart: unless-stopped
    networks:
      - inception-network
    ports:
      - "443:443"
    depends_on:
      - wordpress
    #environment:
    #  DOCKER_TLS_VERIFY:
    #  DOCKER_CERT_PATH:
    #links:
    #  - wordpress
      
    
  mysql:
    image: mariadb:cproesch
    build:
      context: requirements/mariadb
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    restart: unless-stopped
    networks:
      - inception-network
    volumes:
      - mdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass


  wordpress:
    image: wordpress:cproesch
    build:
      context: requirements/wordpress
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    restart: unless-stopped
    networks:
      - inception-network
    depends_on:
      - mysql
    volumes:
      - wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
  #voir si possible de virer le lien 9000:9000 car normalement wordpress n'a
  #pas besoin de communiquer avec l'exterieur, uniquement avec mariadb et nginx
    #ports:
    #  - "9000:9000"
    #links:
    #  - mysql


networks:
  inception-network:
    name: inception-network
    driver: bridge


volumes:
  mdb:  {}
    #driver: local
    #driver_opts:
    #  type: volume
    #  device: /home/cproesch/data/mdb
    #  o: bind
  wp: {}
    #driver: local
    #driver_opts:
    #  type: volume
    #  device: /home/cproesch/data/wp
    #  o: bind
