version: '3'

services:

  nginx:
    image: nginx:cproesch
    build: requirements/nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - inception-network
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    environment:
      DOCKER_TLS_VERIFY:
      DOCKER_CERT_PATH:
     
  mariadb:
    image: mariadb:cproesch
    build:
      context: requirements/mariadb
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception-network
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}

  wordpress:
    image: wordpress:cproesch
    build:
      context: requirements/wordpress
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
    container_name: wordpress
    restart: unless-stopped
    networks:
      - inception-network
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}

networks:
  inception-network:
    name: inception-network
    driver: bridge


volumes:
  mariadb:
    driver: local
    driver_opts:
     type: volume
     device: /home/cproesch/data/mariadb
     o: bind

  wordpress:
    driver: local
    driver_opts:
     type: volume
     device: /home/cproesch/data/wordpress
     o: bind
