version: '3'

services:

  nginx: #name of the container
    image: nginx 
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      DOCKER_TLS_VERIFY:
      DOCKER_CERT_PATH:
    links:
      - wordpress


  wordpress:
    image: wordpress
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORS_DB_PASSWORD: user_pass
      WORDPRESS_DB_NAME: db_name
    links:
      - mysql

    
  mysql:
    image: mariadb
    restart: unless-stopped
    volumes:
      - mdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass


networks:
  default:
    name: inception-network


volumes:
  wp:
    driver: local
    driver_opts:
      type: volume
      device: /home/cproesch/data/wp
  mdb:
    driver: local
    driver_opts:
      type: volume
      device: /home/cproesch/data/mdb


