version: '3'

services:

  nginx: #name of the container
    build: requirements/nginx
    image: nginx:cproesch
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      DOCKER_TLS_VERIFY:
      DOCKER_CERT_PATH:
    links:
      - wordpress

    
  mysql:
    build: requirements/mariadb
    image: mariadb:cproesch
    restart: unless-stopped
    volumes:
      - mdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass


  wordpress:
    #build: requirements/wordpress
    image: wordpress
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
    links:
      - mysql


networks:
  default:
    name: inception-network


volumes:
  mdb:  {}
    #driver: local
    #driver_opts:
    #  type: volume
    #  device: /home/cproesch/data/mdb
    #  o: bind
  wp: {}
    #driver: local
    #driver_opts:
    #  type: volume
    #  device: /home/cproesch/data/wp
    #  o: bind


