version: '3'

# modifier partout cproeschel par cproesch!
services:

  nginx: #name of the container
    image: nginx 
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "443:443" #hostport:containerport
    volumes:
      - /home/cproeschel/data/ngx:/etc/nginx/conf.d #pas sure que ce soit necessaire
    environment: #environmental variables
      DOCKER_TLS_VERIFY:
      DOCKER_CERT_PATH:
    links:
      - wordpress


  wordpress:
    image: wordpress
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - /home/cproeschel/data/wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORS_DB_PASSWORD: user_pass
      # WORDPRESS_DB_NAME: db_nameDPRESS_DB_NAME: db_name
    links:
      - mysql

    
  mysql:
    image: mariadb
    restart: unless-stopped
    volumes:
      - /home/cproeschel/data/mdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass


networks:
  default:
    name: inception-network

volumes:
  /home/cproeschel/data/wp:
    driver: local
  /home/cproeschel/data/mdb:
    driver: local


