FROM debian:buster

#en fait peut-etre pas mariabd-serer, a voir quels paquets installer
RUN apt-get update \
    && apt-get install mariadb-server -y \ 
    && apt-get install vim -y

COPY 

CMD ["", "", ""]
#CMD ["tail", "-f", "/dev/null"]
